### ISSUE TITLE
zbs-operator deployment doc helm install command error

### ISSUE THREAD

**Issue by gxglls** [iomesh/docs#38]
`helm install --namespace iomesh-system --create-namespace iomesh-system my-zbs-operator iomesh/zbs-operator --version 0.1.0`  
改为 
`helm install --namespace iomesh-system --create-namespace my-zbs-operator iomesh/zbs-operator --version 0.1.0`
去掉 --create-namespace 后面的参数

**Comment by fanyang89** [comment]
Fixed
